# What is the Iris Dataset?

Acording to wikipedia, the iris dataset is s a multivariate data set introduced by the British statistician and biologist Ronald Fisher in his 1936 paper The use of multiple measurements in taxonomic problems as an example of linear discriminant analysis.

The dataset included 50 samples from each of the three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample, the length and the width of the sepals and petals, in centimeters.

Using a combination of this information, Fisher developed a linear discriminant model to distinguish the species from each other.


## Iris Setosa
![Image of Iris setosa](https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Kosaciec_szczecinkowaty_Iris_setosa.jpg/330px-Kosaciec_szczecinkowaty_Iris_setosa.jpg)

## Iris Versicolor
![Image of Iris versicolor](https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Iris_versicolor_3.jpg/330px-Iris_versicolor_3.jpg)

## Iris Verginica
![Image of Iris virginica](https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Iris_virginica.jpg/330px-Iris_virginica.jpg)

## Visualising The Data

We can use a python library called panda which is a library for data manipulation and analysis, to import the dataset and investiagte further into what the data set looks like.

In [1]:
# Import Panda
import pandas as pd

# Load the iris data set from a URL.
df = pd.read_csv("https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv")

# Print out the contents of the csv file
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
7             5.0          3.4           1.5          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
9             4.9          3.1           1.5          0.1     setosa
10            5.4          3.7           1.5          0.2     setosa
11            4.8          3.4           1.6          0.2     setosa
12            4.8          3.0           1.4          0.1     setosa
13            4.3          3.0           1.1          0.1     setosa
14            5.8          4.0           1.2          0.2     setosa
15            5.7          4.4           1.5          0.4     setosa
16            5.4          3.9           1.3          0.4     setosa
17            5.1          3.5           1.4          0.3     setosa
18            5.7          3.8           1.7          0.3     setosa
19            5.1          3.8           1.5          0.3     setosa
20            5.4          3.4           1.7          0.2     setosa
21            5.1          3.7           1.5          0.4     setosa
22            4.6          3.6           1.0          0.2     setosa
23            5.1          3.3           1.7          0.5     setosa
24            4.8          3.4           1.9          0.2     setosa
25            5.0          3.0           1.6          0.2     setosa
26            5.0          3.4           1.6          0.4     setosa
27            5.2          3.5           1.5          0.2     setosa
28            5.2          3.4           1.4          0.2     setosa
29            4.7          3.2           1.6          0.2     setosa
..            ...          ...           ...          ...        ...
120           6.9          3.2           5.7          2.3  virginica
121           5.6          2.8           4.9          2.0  virginica
122           7.7          2.8           6.7          2.0  virginica
123           6.3          2.7           4.9          1.8  virginica
124           6.7          3.3           5.7          2.1  virginica
125           7.2          3.2           6.0          1.8  virginica
126           6.2          2.8           4.8          1.8  virginica
127           6.1          3.0           4.9          1.8  virginica
128           6.4          2.8           5.6          2.1  virginica
129           7.2          3.0           5.8          1.6  virginica
130           7.4          2.8           6.1          1.9  virginica
131           7.9          3.8           6.4          2.0  virginica
132           6.4          2.8           5.6          2.2  virginica
133           6.3          2.8           5.1          1.5  virginica
134           6.1          2.6           5.6          1.4  virginica
135           7.7          3.0           6.1          2.3  virginica
136           6.3          3.4           5.6          2.4  virginica
137           6.4          3.1           5.5          1.8  virginica
138           6.0          3.0           4.8          1.8  virginica
139           6.9          3.1           5.4          2.1  virginica
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146

We can also use a handy python library called seaborn which is a statistical data visualization library to create nice plots for us to see how each features characteristics make it unique to its iris species.

In [2]:
# Manage Import
import seaborn as sns

# Import matplotlib because seaborn is based of that, otherwise graphs will not show
import matplotlib.pyplot as plt

sns.pairplot(df, hue="species")



## Using Keras and tenserflow to train our mini neural network

### What is Keras?

Keras is a high-level neural networks API, which runs on top of tensorflow.

In [3]:
# Imports 

import keras as kr
import pandas as pd
import sklearn.preprocessing as pre 
import sklearn.model_selection as mod

C:\Users\dell\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


### Next we need to load in our Iris dataset

In [4]:
## Read Dats
df = pd.read_csv('https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv')

##print(df)

## Split our dataset into an array of these attributes for input into our nural network
inputs = df[['petal_length','petal_width','sepal_length','sepal_width']]

##print(inputs)


### Next we want to convert our species in the dataset to binary numbers so our nural network can understand it easier and more efficient

In [5]:
## LabelBinarizer converts our species to a binary format number , each species will have a unique number 

## Example setosa -> 1,0,0 versicolor -> 0,1,0 virginica -> 0,0,1

encoder = pre.LabelBinarizer()
encoder.fit(df['species'])
outputs = encoder.transform(df['species'])

print(outputs) ## As you can see each of our outputs (Species) is now in a binary number format

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 

### Building our model

The overall idea for our model is that if we give our model this -> [5.1(Petal_Length),3.5(Petal_Width),1.4(Sepal_Length),0.2(Sepal Width)] we want to give us an output of => [1,0,0] (Setosa)

In [6]:
## There are two types of models we can use, sequential and Functional , Sequential is fine in most cases unless:
## multiple different input sources,
## produce multiple output destinations, or
## models that re-use layers.

## Sequential Models lets us add to our models layer-by-layer
model = kr.models.Sequential()

## Layer for our inputs units is basically our neurons
model.add(kr.layers.Dense(units=64, activation='relu',input_dim=4))

## Layer for our outputs 
## Softmax is used for probability distribution as we will be given a probability that it is either of the species
model.add(kr.layers.Dense(units=3, activation='softmax'))

## Neural networks don't optimise from accuracy , they optimise from loss , the goal is to minimise loss
model.compile(loss='categorical_crossentropy',optimizer='sgd',metrics=['accuracy'])





## Split our data

In [13]:
## We want to split our data into training data and test data
## we use the training data to fit the model and testing data to test it.

## Normally we want our training set to be 70% of the data and the test to be 30% 
## Obviusly the bigger the training set the more accurate our model will be.
inputs_train, inputs_test, outputs_train, outputs_test = mod.train_test_split(inputs, outputs, test_size=0.30)

## Our input train has 105 rows 
print(inputs_train)

## Our test train has 45 rows
print(inputs_test)




     petal_length  petal_width  sepal_length  sepal_width
28            1.4          0.2           5.2          3.4
110           5.1          2.0           6.5          3.2
79            3.5          1.0           5.7          2.6
70            4.8          1.8           5.9          3.2
35            1.2          0.2           5.0          3.2
78            4.5          1.5           6.0          2.9
119           5.0          1.5           6.0          2.2
48            1.5          0.2           5.3          3.7
98            3.0          1.1           5.1          2.5
40            1.3          0.3           5.0          3.5
89            4.0          1.3           5.5          2.5
120           5.7          2.3           6.9          3.2
134           5.6          1.4           6.1          2.6
29            1.6          0.2           4.7          3.2
103           5.6          1.8           6.3          2.9
15            1.5          0.4           5.7          4.4
54            

## Train our model

In [18]:
## We use the model.fit function to train our model,

## We fit the model with our inputs_train and outputs_train 

## We also pass an epoch number which means how many times you go through your training set

## the batch size is the iterations it goes over the data , e.g if the sample size was 150 and the batch_size was 10 
## it would go through the data as follows , 1-10, 10-20 etc...

## Note: the smaller the batch size the less memory is used because your training using less data 
## also.. Typically networks train faster with mini-batches

model.fit(inputs_train,outputs_train,epochs=5,batch_size=10)

Epoch 1/5
105/105 [==============================] - 0s 123us/step - loss: 0.3135 - acc: 0.9714
Epoch 2/5
105/105 [==============================] - 0s 95us/step - loss: 0.3035 - acc: 0.9429
Epoch 3/5
105/105 [==============================] - 0s 85us/step - loss: 0.3260 - acc: 0.9143
Epoch 4/5
105/105 [==============================] - 0s 123us/step - loss: 0.3131 - acc: 0.9238
Epoch 5/5
105/105 [==============================] - 0s 133us/step - loss: 0.3022 - acc: 0.9619


## Predictions